# Assignment-4 Excaption Handelling(Selenium)

In [15]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\sharm\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\sharm\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\sharm\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\sharm\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\sharm\anaconda3\lib\site-packages (from selenium) (2023.5.7)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\sharm\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\sharm\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\sharm\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\sharm\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\sharm\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\sharm\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

# Solution of question no. 1

1.	Scrape  	the  	details  of  	most  	viewed  videos  on  	YouTube  	from  	Wikipedia.  	Url 
 = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos You need to find following details:  A) Rank   
B)	Name   
C)	Artist   
D)	Upload date   
E)	Views

In [16]:
# importing libraries
from selenium import webdriver
from time import sleep
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.common.exceptions import NoSuchElementException

In [20]:
# choosing Chrome as our browser
driver=webdriver.Chrome()

In [21]:
# getting in to web page
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [22]:

driver.maximize_window()

In [23]:
# variables for storing scraped data
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]

In [31]:
# scraping all atributes as per question
    
try:
    name=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[1]')
    for i in name:
        Name.append(i.text)
        
except NoSuchElementException:
    Name.append("-")
    
    
try:
    artist=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')
    for k in artist:
        Artist.append(k.text)
        
except NoSuchElementException:
    Artist.append("-")
    
    
try:
    upload_date=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')
    for l in upload_date:
        Upload_date.append(l.text)
        
except NoSuchElementException:
    Upload_date.append("-")
    

try:
    views=driver.find_elements(By.XPATH,'//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')
    for m in views:
        Views.append(m.text)
        
except NoSuchElementException:
    Views.append("-")

In [34]:
#checking lengths
print(len(Name),len(Artist),len(Upload_date),len(Views))

30 30 30 30

In [35]:
#creating the dataframe
df1=pd.DataFrame({"Name":Name,"Artist":Artist,"Upload_date":Upload_date,"Views":Views})
df1

,Name,Artist,Upload_date,Views
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.32
1,"""Despacito""[10]",Luis Fonsi,"January 12, 2017",8.41
2,"""Johny Johny Yes Papa""[18]",LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.89
3,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"May 2, 2018",6.66
4,"""Shape of You""[20]",Ed Sheeran,"January 30, 2017",6.23
5,"""See You Again""[23]",Wiz Khalifa,"April 6, 2015",6.22
6,"""Wheels on the Bus""[28]",Cocomelon - Nursery Rhymes,"May 24, 2018",6.01
7,"""Phonics Song with Two Words""[29]",ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.75
8,"""Uptown Funk""[30]",Mark Ronson,"November 19, 2014",5.18
9,"""Gangnam Style""[31]",Psy,"July 15, 2012",5.10
10,"""Learning Colors – Colorful Eggs on a Farm""[36]",Miroshka TV,"February 27, 2018",5.09
11,"""Dame Tu Cosita""[37]",Ultra Records,"April 5, 2018",4.59
12,"""Masha and the Bear – Recipe for Disaster""[38]",Get Movies,"January 31, 2012",4.57
13,"""Axel F""[39]",Crazy Frog,"June 16, 2009",4.45
14,"""Sugar""[40]",Maroon 5,"January 14, 2015",4.02
15,"""Baa Baa Black Sheep""[41]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.01
16,"""Counting Stars""[42]",OneRepublic,"May 31, 2013",4.00
17,"""Lakdi Ki Kathi""[43]",Jingle Toons,"June 14, 2018",3.98
18,"""Roar""[44]",Katy Perry,"September 5, 2013",3.98
19,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.89
20,"""Sorry""[46]",Justin Bieber,"October 22, 2015",3.78
21,"""Shree Hanuman Chalisa""[47]",T-Series Bhakti Sagar,"May 10, 2011",3.77
22,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.76
23,"""Thinking Out Loud""[49]",Ed Sheeran,"October 7, 2014",3.75
24,"""Perfect""[50]",Ed Sheeran,"November 9, 2017",3.70
25,"""Dark Horse""[51]",Katy Perry,"February 20, 2014",3.70
26,"""Let Her Go""[52]",Passenger,"July 25, 2012",3.64
27,"""Faded""[53]",Alan Walker,"December 3, 2015",3.60
28,"""Girls Like You""[54]",Maroon 5,"May 31, 2018",3.58
29,"""Lean On""[55]",Major Lazer Official,"March 22, 2015",3.57

# Solution for question no. 2

2.	Scrape the details team India’s international fixtures from bcci.tv.   
Url = https://www.bcci.tv/.   
You need to find following details:   
A)	Series   
B)	Place   
C)	Date   
D)	Time   
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [18]:
# importing libraries
from selenium import webdriver
from time import sleep
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.common.exceptions import NoSuchElementException

In [19]:
# connecting to google chrome
driver=webdriver.Chrome()

In [20]:
# getting in to bcci page
driver.get("https://www.bcci.tv/")

In [21]:
driver.maximize_window()

In [22]:
# clicking in for fixters
fixtur=driver.find_element(By.XPATH,"/html/body/header/div[3]/div[2]/ul/div[1]/a[2]")
fixtur.click()

In [24]:
# taking variables for storing data
Series = []
Place = []
Date = []
Time = []

In [25]:
# scraping our required attributes

try:
    series=driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
    for s in series:
        Series.append(s.text)
except NoSuchElementException:
    Series.append("-")
    
try:
    place=driver.find_elements(By.XPATH,'//div[@class="match-place ng-scope"]')
    for p in place:
        Place.append(p.text)
except NoSuchElementException:
    Place.append("-")
    
try:
    date=driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
    for d in date:
        Date.append(d.text)
except NoSuchElementException:
    Date.append("-")
    
try:
    time=driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
    for t in time:
        Time.append(t.text)
except NoSuchElementException:
    Time.append("-")

In [27]:
# creating DataFrame
df2=pd.DataFrame({"Series":Series,"Place": Place, "Date":Date,"Time":Time})
df2

,Series,Place,Date,Time
0,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","5 JUNE, 2024",8:00 PM IST
1,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","9 JUNE, 2024",8:00 PM IST
2,ICC MENS T20 WORLD CUP 2024,"Nassau County International Cricket Stadium, N...","12 JUNE, 2024",8:00 PM IST
3,ICC MENS T20 WORLD CUP 2024,"Central Broward Park & Broward County Stadium,...","15 JUNE, 2024",8:00 PM IST
4,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","6 JULY, 2024",8:00 PM IST
5,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","7 JULY, 2024",8:00 PM IST
6,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","10 JULY, 2024",8:00 PM IST
7,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","13 JULY, 2024",8:00 PM IST
8,INDIA TOUR OF ZIMBABWE 2024,"Harare Sports Club, Harare","14 JULY, 2024",8:00 PM IST

# Solution for question no. 3

3.	Scrape the details of State-wise GDP of India from statisticstime.com.   
Url = http://statisticstimes.com/   
You have to find following details: A) Rank   B) State   
C)	GSDP(18-19)- at current prices   
D)	GSDP(19-20)- at current prices   
E)	Share(18-19)   
F)	GDP($ billion)   
Note: - From statisticstimes home page you have to reach to economy page through code.

In [3]:
# getting in to webbrowser
driver=webdriver.Chrome()

In [4]:
#getting in to web page
driver.get(" http://statisticstimes.com/")

In [5]:
driver.maximize_window()

In [6]:
# entering in economy section and clicking for india
economy=driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/button")
economy.click()

In [9]:
india=driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
india.click()

In [7]:
# variables for storing data
Rank = []
State = []
GSDP_A = []
GSDP_B = []
Share = []
GDP = []

In [10]:
# scraping data for all attributes
try:
    
    rank=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[1]')
    for r in rank:
        Rank.append(r.text)
        sleep(1)
except NoSuchElementException:
    Rank.append("na")
    
try:
    
    state=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[2]')
    for s in state:
        State.append(s.text)
        sleep(1)
except NoSuchElementException:
    State.append("na")
    
try:
    
    GSDP=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[3]')
    for g in GSDP:
        GSDP_A.append(g.text)
        sleep(1)
except NoSuchElementException:
    GSDP_A.append("na")
    
try:
    
    GSDP_=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[4]')
    for gs in GSDP_:
        GSDP_B.append(gs.text)
        sleep(1)
except NoSuchElementException:
    GSDP_B.append("na")
    
try:
    
    share=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[6]')
    for h in share:
        Share.append(h.text)
        sleep(1)
except NoSuchElementException:
    Share.append("na")
    
try:
    
    GDP_=driver.find_elements(By.XPATH,'//tr[@class="odd"]/td[7]')
    for p in GDP_:
        GDP.append(p.text)
        sleep(1)
except NoSuchElementException:
    GDP.append("na")

In [12]:
# checking lengths
print(len(Rank),len(State),len(GSDP_A),len(GSDP_B),len(Share),len(GDP))

34 34 34 34 34 34

 Note: GSDP for (18-19) & (19-20) was not available in page thats why i've scraped for 23  &24

In [14]:
# creating DataFrame
df=pd.DataFrame({"Rank":Rank,"State":State,"GSDP_(23-24)":GSDP_A,"GSDP_(22-23)":GSDP_B,"Share":Share,"GDP($ billion)":GDP})
df

,Rank,State,GSDP_(23-24),GSDP_(22-23),Share,GDP($ billion)
0,1,Maharashtra,-,-,13.17%,414.928
1,3,Karnataka,"2,500,733","2,269,995",8.38%,264.080
2,5,Gujarat,-,"2,230,609",8.17%,257.484
3,7,Rajasthan,"1,524,030","1,365,849",5.06%,159.334
4,9,Telangana,"1,463,960","1,308,034",4.76%,150.084
5,11,Kerala,-,"1,046,188",3.96%,124.764
6,13,Haryana,"1,095,535","984,055",3.68%,116.001
7,15,Bihar,-,"751,396",2.76%,86.817
8,17,Assam,"565,401","493,167",1.74%,54.930
9,19,Jharkhand,-,"393,722",1.52%,47.909
10,21,Jammu & Kashmir,"246,465","224,226",0.82%,25.813
11,23,Goa,-,"93,672",0.36%,11.250
12,25,Chandigarh,-,"54,285",0.20%,6.154
13,27,Meghalaya,"47,381","42,697",0.16%,5.178
14,29,Manipur,-,-,0.16%,4.885
15,31,Nagaland,-,"35,643",0.13%,4.144
16,33,Andaman & Nicobar Islands,-,-,0.04%,1.385
17,1,Maharashtra,-,-,13.03%,-
18,3,Karnataka,"2,261,867","2,055,658",8.67%,"1,263,925"
19,5,Gujarat,-,"1,946,334",8.23%,-
20,7,Rajasthan,"1,366,626","1,222,507",5.18%,"737,042"
21,9,Telangana,"1,326,022","1,184,237",4.93%,"679,552"
22,11,Kerala,-,"933,564",3.99%,-
23,13,Haryana,"985,877","885,029",3.77%,"561,368"
24,15,Odisha,"749,809","670,196",2.81%,"443,233"
25,17,Assam,"487,584","428,072",1.77%,"288,842"
26,19,Jharkhand,-,"360,689",1.58%,-
27,21,Jammu & Kashmir,"200,046","181,383",0.76%,"108,830"
28,23,Goa,-,"83,711",0.36%,-
29,25,Chandigarh,-,"48,261",0.20%,-
30,27,Meghalaya,"42,214","37,925",0.17%,"23,063"
31,29,Sikkim,-,"35,670",0.15%,-
32,31,Nagaland,-,"30,957",0.13%,-
33,33,Andaman & Nicobar Islands,-,-,0.04%,-

# Solution of question no. 4

4.	Scrape the details of trending repositories on Github.com.   
Url = https://github.com/   
You have to find the following details:   
A)	Repository title   
B)	Repository description   
C)	Contributors count   
D)	Language used   
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [47]:
# importing libraries
from selenium import webdriver
from time import sleep
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.common.exceptions import NoSuchElementException

In [18]:
# geting in Chrome browser
driver=webdriver.Chrome()

In [19]:
# findingout github page through url
driver.get("https://github.com/")

In [16]:
driver.maximize_window()

In [20]:
# clicking open source and then trending as per question
os=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button")
os.click()
sleep(1)
trending=driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a")
trending.click()
sleep(1)

In [22]:
# fetching urls of repositeries
Url=[]
url=driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]/a')
for i in url:
    Url.append(i.get_attribute("href"))
    sleep(1)

In [23]:
len(Url)

25

In [31]:
# taking variebles for storing scraped data
Repository_title = []
Repository_description =[]
Contributors_count = []
Language_used = []

In [32]:
for a in Url:        #using url for scraping indivisually each repositery
    driver.get(a)
    sleep(2)

# scraping data for all attributes indivisually
    try:
        
        title=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/div/div[1]/div[1]/div/strong/a')
        Repository_title.append(title.text)
        sleep(1)
            
    except NoSuchElementException:
        Repository_title.append("-")
    
    try:
        
        description=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/div/div[2]/div/p')
        Repository_description.append(description.text)
        sleep(1)
        
    except NoSuchElementException:
        Repository_description.append("-")
     
    try:
        
        Contributors=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[5]/div/h2/a/span')
        Contributors_count.append(Contributors.text)
        sleep(1) 
    except NoSuchElementException:
        Contributors_count.append("-")
    
    try:
        Language=driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[6]/div/ul/li[1]/a/span[1]')
        Language_used.append(Language.text)
        sleep(1)
    except NoSuchElementException:
        Language_used.append("-")

In [33]:

#checking lengths
print(len(Repository_title),len(Repository_description),len(Contributors_count),len(Language_used))

25 25 25 25

In [34]:
#creating dataframe
df4=pd.DataFrame({"Language_used":Language_used,"Repository_title":Repository_title, "Repository_description":Repository_description, "Contributors_count":Contributors_count})
df4

,Language_used,Repository_title,Repository_description,Contributors_count
0,-,plandex,An AI coding engine for complex tasks,-
1,Python,SWE-agent,SWE-agent takes a GitHub issue and tries to au...,14
2,Rust,ore-cli,-,4
3,Python,ragflow,RAGFlow is an open-source RAG (Retrieval-Augme...,11
4,-,ore,-,-
5,-,nlw-unite-react,Aplicação front-end em React desenvolvida dura...,-
6,Go,LLocalSearch,LLocalSearch is a completely locally running s...,6
7,-,gpt-author,-,-
8,HTML,aurora,free,8
9,Shell,availup,-,3
10,JavaScript,langflow,⛓️ Langflow is a dynamic graph where each node...,85
11,TypeScript,superset,Apache Superset is a Data Visualization and Da...,"1,064"
12,-,computer-science,🎓 Path to a free self-taught education in Comp...,140
13,Objective-C,firebase-ios-sdk,Firebase SDK for Apple App Development,221
14,-,nlw-unite-nodejs,Back-end em Node.js desenvolvido durante o NLW...,-
15,-,SaaS-Boilerplate,🚀🎉📚 SaaS Boilerplate built with Next.js + Tail...,-
16,Lua,AstroNvim,AstroNvim is an aesthetic and feature-rich neo...,79
17,TypeScript,refine,"A React Framework for building internal tools,...",221
18,-,uv,An extremely fast Python package installer and...,-
19,-,FreeTube,An Open Source YouTube app for privacy,-
20,-,ui,Simple UI examples from my social media,-
21,TypeScript,setup-node,Set up your GitHub Actions workflow with a spe...,90
22,TypeScript,openui,OpenUI let's you describe UI using your imagin...,7
23,Zig,bun,"Incredibly fast JavaScript runtime, bundler, t...",585
24,Rust,avail,-,36

# Solution for question no. 5

5.	Scrape the details of top 100 songs on billiboard.com. Url = https:/www.billboard.com/  You have to find the following details:   
A)	Song name   
B)	Artist name   
C)	Last week rank   
D)	Peak rank   
E)	Weeks on board   
 
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [3]:
# geting in Chrome browser
driver=webdriver.Chrome()

In [4]:
# findingout page through url
driver.get("https:/www.billboard.com/")

In [5]:
driver.maximize_window()

In [11]:
# clicking on menu icon
menu=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button')
menu.click()

In [12]:
# clicking on charts
charts=driver.find_element(By.XPATH,"/html/body/div[3]/div[9]/div/div/div/ul/li[1]/h3/a")
charts.click()

In [13]:
# finding & clicking our hot 100 songs
hot_100=driver.find_element(By.XPATH,"/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a")
hot_100.click()

In [14]:
# taking variebles for storing scraped data
Song_name = []
Artist_name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [15]:
#scraping data for all attributes
song_name=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/h3')
for i in song_name:
    Song_name.append(i.text)
    sleep(1)
    
artist_name=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[1]/span[1]')
for j in artist_name:
    Artist_name.append(j.text)
    sleep(1)
    
last_week_rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1"][1]/span')
for k in last_week_rank:
    Last_week_rank.append(k.text)
    sleep(1)
    
peak_rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light lrv-u-flex-grow-1"][2]/span')
for l in peak_rank:
    Peak_rank.append(l.text)
    sleep(1)
    
weeks_on_board=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max lrv-u-flex-grow-1"][2]/span')
for m in Weeks_on_board:
    weeks_on_board.append(m.text)
    sleep(1)

In [16]:
#checking lenghts
print(len(Song_name),len(Artist_name),len(Last_week_rank),len(Last_week_rank),len(Peak_rank))

100 100 100 100 100

In [17]:
# creating dataframe
df = pd.DataFrame({"Song_name":Song_name,"Artist_name":Artist_name,"Last_week_rank":Last_week_rank,"Peak_rank":Peak_rank})
df

,Song_name,Artist_name,Last_week_rank,Peak_rank
0,Like That,"Future, Metro Boomin & Kendrick Lamar",-,1
1,Type Shit,"Future, Metro Boomin, Travis Scott & Playboi C...",-,2
2,Beautiful Things,Benson Boone,2,2
3,Lose Control,Teddy Swims,1,1
4,Too Sweet,Hozier,-,5
...,...,...,...,...
95,La Victima,Xavi,77,46
96,Tucson Too Late,Jordan Davis,81,81
97,Empire Now,Hozier,-,98
98,Girl I've Always Been,Olivia Rodrigo,-,99
99,Outskirts,Sam Hunt,92,92

# Solution of question no. 6

6.	Scrape the details of Highest selling novels.   
A)	Book name   
B)	Author name   
C)	Volumes sold   
D)	Publisher   
E)	Genre   
 
Url - https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare

In [17]:
#importing libraries
import pandas as pd
from selenium import webdriver
from time import sleep
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.common.exceptions import NoSuchElementException, ElementNotInteractableException

In [18]:
#opening chrome browser
driver=webdriver.Chrome()

In [19]:
# getting in to webpage
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [20]:
driver.maximize_window()

In [27]:
#for storing scraped data
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

In [28]:
#finding and storing our data

try:
    book=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
    for i in book:
        Book_name.append(i.text)
        
except NoSuchElementException:
    Book_name.append("-")
    sleep(1)
    
    
try:
    author_name=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
    for j in author_name:
        Author_name.append(j.text)
        
except NoSuchElementException:
    Author_name.append("-")
    sleep(1)
    
try:
    volumes_sold=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
    for k in volumes_sold:
        Volumes_sold.append(k.text)
        
except NoSuchElementException:
    Volumes_sold.append("-")
    sleep(1)
    
try:
    publisher=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
    for l in publisher:
        Publisher.append(l.text)
        
except NoSuchElementException:
    Publisher.append("-")
    sleep(1)
    
try:
    genre=driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
    for m in genre:
        Genre.append(m.text)
        
except NoSuchElementException:
    Genre.append("-")
    sleep(1)

In [29]:
print(len(Book_name),len(Author_name),len(Volumes_sold),len(Publisher),len(Genre))

100 100 100 100 100

In [31]:
# creating DataFrame
df6= pd.DataFrame({"Book_name":Book_name,"Author_name":Author_name,"Volumes_sold":Volumes_sold,
                  "Publisher":Publisher,"Genre":Genre})
df6

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Solution for question no.7

 7.	Scrape the details most watched tv series of all time from imdb.com.   
Url = https://www.imdb.com/list/ls095964455/ You have to find the following details:   
A)	Name   
B)	Year span   
C)	Genre   
D)	Run time   
E)	Ratings   
F)	Votes

In [46]:
#opening chrome browser
driver=webdriver.Chrome()

In [38]:
driver.maximize_window()

In [41]:
driver.get("http://www.imdb.com/list/ls095964455/")

# 404 page not found

# Solution for question no.8

8.	Details of Datasets from UCI machine learning repositories.   
Url = https://archive.ics.uci.edu/  You have to find the following details:   
A)	Dataset name   
B)	Data type   
C)	Task   
D)	Attribute type   
E)	No of instances   
F)	No of attribute 
G) Year   
 
Note: - from the home page you have to go to the Show All Dataset page through code.

In [53]:
#importing libraries
import pandas as pd
from selenium import webdriver
from time import sleep
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
from selenium.common.exceptions import NoSuchElementException

In [74]:
#opening chrome browser
driver=webdriver.Chrome()

In [75]:
driver.maximize_window()

In [76]:
# getting in to the webpage
driver.get("https://archive.ics.uci.edu/")

In [77]:
all_dataset=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
all_dataset.click()

In [78]:
# collecting urls for scraping indivisualy each 
urls=[]

url=driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
for i in url:
    urls.append(i.get_attribute("href"))
    sleep(1)

In [79]:
len(urls)

10

In [80]:
#taking variables for storing scraped data
Dataset_name = []   
Data_type  = [] 
Task  = [] 
Attribute_type = []  
No_of_instances = []  
No_of_attribute = []
Year = []

In [81]:

for a in  urls:         # taking scraped urls one by one
    driver.get(a)
    sleep(5)

# extracting data from webpage
    try:
        dataset_name=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/div/h1")
        Dataset_name.append(dataset_name.text)
        sleep(1)
            
    except NoSuchElementException:
        Dataset_name.append("-")
        
        
    try:
        data_type=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[1]/p")
        Data_type.append(data_type.text)
            
    except NoSuchElementException:
        Data_type.append("-")
    
    try:
        task=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p")
        Task.append(task.text)
            
    except NoSuchElementException:
        Task.append("-")
    
    
    try:
        attribute_type=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p")
        Attribute_type.append(attribute_type.text)
            
    except NoSuchElementException:
        Attribute_type.append("-")
    
   
    try:
        no_of_instances=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p")
        No_of_instances.append(no_of_instances.text)
            
    except NoSuchElementException:
        No_of_instances.append("-")
        
        
    try:
        no_of_attribute=driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[6]/h1")
        No_of_attribute.append(no_of_attribute.text)
        sleep(1)
            
    except NoSuchElementException:
        No_of_attribute.append("-")
    
    
    try:
        year=driver.find_element(By.XPATH,'//h2[@class="text-sm text-primary-content"]')
        Year.append(year.text)
        sleep(1)
            
    except NoSuchElementException :
        Year.append("Not_present")

In [82]:
# checking length of all attributes
print(len(Dataset_name),len(Data_type),len(Task),len(Attribute_type),len(No_of_instances),len(No_of_attribute),len(Year))

10 10 10 10 10 10 10

In [83]:
#creating DataFrame
df8=pd.DataFrame({"Dataset_name":Dataset_name,"Data_type":Data_type,"Task":Task,"Attribute_type":Attribute_type,
                 "No_of_instances":No_of_instances,"No_of_attribute":No_of_attribute,"Year":Year})
df8

,Dataset_name,Data_type,Task,Attribute_type,No_of_instances,No_of_attribute,Year
0,Iris,Tabular,Classification,Real,150,# Features,Donated on 6/30/1988
1,Dry Bean,Multivariate,Classification,"Integer, Real",13611,# Features,Donated on 9/13/2020
2,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,# Features,Donated on 6/30/1988
3,Rice (Cammeo and Osmancik),Multivariate,Classification,Real,3810,# Features,Donated on 10/5/2019
4,Adult,Multivariate,Classification,"Categorical, Integer",48842,# Features,Donated on 4/30/1996
5,Raisin,Multivariate,Classification,"Real, Integer",900,# Features,Donated on 8/13/2023
6,Breast Cancer Wisconsin (Diagnostic),Multivariate,Classification,Real,569,# Features,Donated on 10/31/1995
7,Wine,Tabular,Classification,"Integer, Real",178,# Features,Donated on 6/30/1991
8,Wine Quality,Multivariate,"Classification, Regression",Real,4898,# Features,Donated on 10/6/2009
9,Diabetes,"Multivariate, Time-Series",Classification,"Categorical, Integer",1,# Features,Not_present

# Done!!